### PR TITLE
Replace shortid to nanoid

### PR DESCRIPTION
**Pull request by ai**
Hi. Thanks for an awesome project. I found the way how to make it a little better. By replacing unqiue ID generator from `shortid` to [`nanoid`](https://github.com/ai/nanoid).

1. `shortid` is not maintained anymore (and issue tracker has many [important issues](https://github.com/dylang/shortid/issues)). I tried to took maintenance, but found that I can’t fix `shortid` with keeping API.
2. `nanoid` is just [179 bytes](https://github.com/ai/nanoid/blob/master/package.json#L64-L67). `shortid` is 2 times bigger (about 0.5 KB).
3. `nanoid` is [10x times faster](https://github.com/ai/nanoid#benchmark) than `shortid`.

@serikjensen I kept old ID size, everything will be the same for the user.

### CODE REVIEW

**Comment by ai** [comment]
Sorry for changing `npm-shrinkwrap.json`. I use npm 5 and it updates checksums from sha1 to sha256. Feel free to regenerate it back.

**Comment by junyper** [comment]
Looks like spam.

**Comment by ai** [comment]
@junyper it is not spam 😅 I am creator of PostCSS and Autoprefixer, you maybe use them.

And shortid really have all this problem, it is not maintained and bigger than nanoid.

**Comment by junyper** [comment]
OK. Sorry--we got a similar request on our other repo with similar content, so it seemed spammy. :) I'll look into this more.

**Comment by ai** [comment]
I understand. Just too both project will win on ID generator changes 😊

**Comment by ai** [comment]
@junyper do you have any question about nanoid?

**Comment by ai** [comment]
Many big projects already replaced and happy with `nanoid`

[react-alert](https://github.com/schiehll/react-alert) [json-server](https://github.com/typicode/json-server/pull/655)

**Comment by ai** [comment]
@serikjensen  maybe you can again request a approve from @junyper

A lot of projects migrated from `shortid` for this month.

**Comment by ai** [comment]
@arlodesign should we move to `nanoid` here too since we moved in `instructure-ui`. Same dependency = smaller bundle.

**Comment by junyper** [comment]
I'm closing this because we've deprecated this project and pulled everything into the instructure-ui repo.

**Pull request closed without merging**
